#!/bin/sh

BUCKET=pdx-schedule-processed-data
FUNCTION_NAME=load

gcloud functions deploy $FUNCTION_NAME \
  --timeout=540 \
  --memory=1024MB \
  --runtime python37 \
  --trigger-bucket=$BUCKET \
  --region us-central1
